# Configurazione persistenza: jdbc (Database), csv (File System), demo (In-Memory RAM)
persistence=jdbc

# Configurazione Database MySQL
db.url=jdbc:mysql://localhost:3306/ortogest?createDatabaseIfNotExist=true
db.user=root
db.password=root
